#FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
#WORKDIR /app
#
## copy csproj and restore as distinct layers
#COPY *.sln .
#COPY MyWebApp/*.csproj ./MyWebApp/
#RUN dotnet restore
#
## copy everything else and build app
#COPY MyWebApp/. ./MyWebApp/
#WORKDIR /app/MyWebApp
#RUN dotnet publish -c Release -o out
#
#FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
#WORKDIR /app
#COPY --from=build /app/MyWebApp/out ./
#ENTRYPOINT ["dotnet", "MyWebApp.dll"]

# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY MyWebApp/*.csproj ./MyWebApp/
RUN dotnet restore

# copy everything else and build app
COPY MyWebApp/. ./MyWebApp/
WORKDIR /source/MyWebApp
RUN dotnet publish -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "MyWebApp"]